name: frontend
description: "AynovaX Enterprise Interface"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ----------------------------------------------------------
  # Core Logic Dependencies
  # ----------------------------------------------------------
  http: ^1.2.0           
  provider: ^6.1.1        #
  file_picker: ^8.0.0     
  
  # ----------------------------------------------------------
  # UI & Design Dependencies
  # ----------------------------------------------------------
  google_fonts: ^6.1.0    
  animate_do: ^3.3.2     
  cupertino_icons: ^1.0.6 
  flutter_markdown: ^0.6.14
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true